<div class="container">

  <form class="form-addmold" method="post">
    <h2 class="form-addmold-heading">Date matrita</h2>

    <table class="table table-bordered">
	    <tbody>
	      <tr>
	        <td>Denumier reper:</td>
	        <td><b><input type="text" name="denumire_reper"></b></td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Cod reper:</td>
	        <td> <input type="text" name="cod_reper"> </td>
	        <td>Cantitate:</td>
	        <td><input type="text" name="cantitate"> buc/mc</td>
	      </tr>
	      <tr>
	        <td>Cod matrita:</td>
	        <td> <input type="text" name="cod_matrita"> </td>
	        <td>Ciclu inj PP:</td>
	        <td><input type="text" name="ciclu_inj"> sec</td>
	      </tr>
	      <tr>
	        <td>Nr. de cuiburi:</td>
	        <td><input type="text" name="nr_cuiburi"></td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Greutate culee[g]:</td>
	        <td><input type="text" name="greutate_culee"></td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Greutate reper fara culee[g]:</td>
	        <td><input type="text" name="greutate_fara_cule"></td>
	        <td>Dim. matrita [h x l x L]:</td>
	        <td>&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Dimensiuni reper [mm x mm]:</td>
	        <td><input type="text" name="dimensiuni_reper"></td>
	        <td colspan="2"><input type="text" name="dim_matrita_h"> h</td>
	      </tr>
	      <tr>
	        <td>Numar rezistente</td>
	        <td><input type="text" name="numar_rezistente"></td>
	        <td colspan="2"><input type="text" name="dim_matrita_lat"> l</td>
	      </tr>
	      <tr>
	        <td>Diametru inel de centrare:</td>
	        <td><input type="text" name="diametru_inel_centrare"></td>
	        <td colspan="2"><input type="text" name="dim_matrita_lung"> L</td>
	      </tr>
	    </tbody>
	  </table>

	  <table class="table table-bordered">
	    <tbody>
	      <tr>
	        <td><b>Pregatire matrita:</b>
	        	<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">ungere coloane</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">modif. poanson data</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">modif. poanson material</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">verificat duza calda</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">verificat functionare bacuri</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="pregatire_matrita">verificat pozitie bacuri</label>
				</div>
	        </td>
	        <td>&nbsp;</td>
	      </tr>
	      <tr>
	        <td><b>Demontare matrita de pe masina:</b>
	        	<div class="radio">
				  <label><input type="radio" name="demontare_matrita_masina">Verificat ultima injectie</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="demontare_matrita_masina">verificat pozitie bacuri</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="demontare_matrita_masina">suflat aer comprimat</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="demontare_matrita_masina">conservat matrit</label>
				</div>
				</div>
	        </td>
	        <td><b><u>Observatii</u></b></td>
	      </tr>
      	</tbody>
	  </table>

	  <table class="table table-bordered">
	    <tbody>
	      <tr>
	      	<td rowspan="2">Rezistente</td>
	      	<td rowspan="2">Cuiburi</td>
	      	<td colspan="2" rowspan="2">Legaturi rezistente</td>
	      	<td colspan="2">legaturi sonde</td>
	      	<td rowspan="2">&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>+</td>
      	  	<td>-</td>
      	  </tr>
      	  <tr>
      	  	<td>1</td>
      	  	<td><input type="text" name="cuib1"></td>
      	  	<td><input type="text" name="legaturi_rezistetnte_a1"></td>
      	  	<td><input type="text" name="legaturi_rezistetnte_b1"></td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>2</td>
      	  	<td><input type="text" name="cuib2"></td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>3</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>4</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>5</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>6</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>7</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>8</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>9</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>10</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	</tbody>
	  </table>
	  
	  <table class="table table-bordered">
	    <tbody>
	      <tr>
			<td>1 Rezistente cuib</td>
			<td>4x80 TC</td>
			<td>8 buc</td>
  	  	  </tr>
  	  	  <tr>
			<td>2 Rezistenta centrala</td>
			<td>6,5x80 TC 1 buc</td>
			<td>1 buc</td>
  	  	  </tr>
  	  	  <tr>
			<td>3 rezistenta bloc</td>
			<td>9,5x298 TC 1 buc</td>
			<td>1 buc</td>
  	  	  </tr>
      	</tbody>
	  </table>
	  <p>inel O 6x2</p>
  </form>

</div>
