<div class="container">

  <form class="form-material" method="post">
    <h2 class="form-material-heading">Adauga material</h2>
    <label for="inputName">Nume</label>
    <input type="text" id="inputName" name="name" class="form-control" placeholder="Nume" required autofocus>
    <label for="inputfactor">Factor de multiplicare</label>
    <input type="text" id="inputfactor" name="factor" class="form-control" placeholder="Factor de multiplicare, ex 1.95" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Salveaza</button>
  </form>

</div>