<div class="container">

  <form class="form-signin" method="post">
    <h2 class="form-signin-heading">Adauga utilizator</h2>
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email" required autofocus>
    <label for="inputPassword" class="sr-only">Parola</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Parola" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Salveaza</button>
  </form>

</div>