<div class="container">

  <form class="form-material" method="post">
    <h2 class="form-material-heading">Modifica material</h2>
    <label for="inputName">Nume</label>
    <input type="text" id="inputName" name="name" class="form-control" placeholder="Nume" required autofocus value="<?= $this->material['name']?>">
    <label for="inputfactor">Factor de multiplicare</label>
    <input type="text" id="inputfactor" name="factor" class="form-control" placeholder="Factor de multiplicare" required value="<?= $this->material['factor']?>">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Salveaza</button>
  </form>

</div>