<div class="container">
  <div class="table-responsive rounded">
    <table class="table table-hover table-bordered table-secondary">
      <tr>
        <th>CodProdus</th>
        <td colspan="4">76618536015</td>
      </tr>
      <tr>
        <th>Produs</th>
        <th>Ralu Flow #2</th>
        <th>&nbsp;</th>
        <th>Kg/mc</th>
        <th>g/buc</th>
      </tr>
      <tr>
        <th>Material</th>
        <td>PP</td>
        <th>PP</th>
        <td>&nbsp;</td>
        <td>1.67</td>
      </tr>
      <tr>
        <th>Greutate  Kg/mc</th>
        <td>55</td>
        <th>PP GF</th>
        <td>66</td>
        <td>2.00</td>
      </tr>
      <tr>
        <th>Productie 24h</th>
        <td>1.2</td>
        <th>PES</th>
        <td>101.75</td>
        <td>3.08</td>
      </tr>
      <tr>
        <th>Greutate /buc</th>
        <td>1.67</td>
        <th>PPS</th>
        <td>99</td>
        <td>3.00</td>
      </tr>
      <tr>
        <th>TimpInjectie [sec]</th>
        <td>1.92</td>
        <th>PVDF</th>
        <td>110</td>
        <td>3.33</td>
      </tr>
      <tr>
        <th>MasinaTip</th>
        <td>&nbsp;</td>
        <th>FEP</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Buc/mc</th>
        <td>33000</td>
        <th>PFA</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Nr Matrita</th>
        <td>&nbsp;</td>
        <th>E-CTFE</th>
        <td>108.35</td>
        <td>3.28</td>
      </tr>
      <tr>
        <th>Nr cuiburi/matrita</th>
        <td>6</td>
        <th>E-TFE</th>
        <td>121</td>
        <td>3.67</td>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
        <th>NDPE</th>
        <td>60.5</td>
        <td>1.83</td>
      </tr>
    </table>
  </div>
  <div class="table-responsive rounded">
    <table class="table table-hover table-bordered table-light">
      <tr>
        <th>CodProdus</th>
        <td colspan="4">&nbsp;</td>
      </tr>
      <tr>
        <th>Produs</th>
        <th>Ralu Flow #2</th>
        <th>&nbsp;</th>
        <th>Kg/mc</th>
        <th>g/buc</th>
      </tr>
      <tr>
        <th>Material</th>
        <td>PP</td>
        <th>PP</th>
        <td>&nbsp;</td>
        <td>1.67</td>
      </tr>
      <tr>
        <th>Greutate  Kg/mc</th>
        <td>55</td>
        <th>PP GF</th>
        <td>66</td>
        <td>2.00</td>
      </tr>
      <tr>
        <th>Productie 24h</th>
        <td>1.2</td>
        <th>PES</th>
        <td>101.75</td>
        <td>3.08</td>
      </tr>
      <tr>
        <th>Greutate /buc</th>
        <td>1.67</td>
        <th>PPS</th>
        <td>99</td>
        <td>3.00</td>
      </tr>
      <tr>
        <th>TimpInjectie [sec]</th>
        <td>1.92</td>
        <th>PVDF</th>
        <td>110</td>
        <td>3.33</td>
      </tr>
      <tr>
        <th>MasinaTip</th>
        <td>&nbsp;</td>
        <th>FEP</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Buc/mc</th>
        <td>33000</td>
        <th>PFA</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Nr Matrita</th>
        <td>&nbsp;</td>
        <th>E-CTFE</th>
        <td>108.35</td>
        <td>3.28</td>
      </tr>
      <tr>
        <th>Nr cuiburi/matrita</th>
        <td>6</td>
        <th>E-TFE</th>
        <td>121</td>
        <td>3.67</td>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
        <th>NDPE</th>
        <td>60.5</td>
        <td>1.83</td>
      </tr>
    </table>
  </div>
  <div class="table-responsive rounded">
    <table class="table table-hover table-bordered table-secondary">
      <tr>
        <th>CodProdus</th>
        <td colspan="4">76618536015</td>
      </tr>
      <tr>
        <th>Produs</th>
        <th>Ralu Flow #2</th>
        <th>&nbsp;</th>
        <th>Kg/mc</th>
        <th>g/buc</th>
      </tr>
      <tr>
        <th>Material</th>
        <td>PP</td>
        <th>PP</th>
        <td>&nbsp;</td>
        <td>1.67</td>
      </tr>
      <tr>
        <th>Greutate  Kg/mc</th>
        <td>55</td>
        <th>PP GF</th>
        <td>66</td>
        <td>2.00</td>
      </tr>
      <tr>
        <th>Productie 24h</th>
        <td>1.2</td>
        <th>PES</th>
        <td>101.75</td>
        <td>3.08</td>
      </tr>
      <tr>
        <th>Greutate /buc</th>
        <td>1.67</td>
        <th>PPS</th>
        <td>99</td>
        <td>3.00</td>
      </tr>
      <tr>
        <th>TimpInjectie [sec]</th>
        <td>1.92</td>
        <th>PVDF</th>
        <td>110</td>
        <td>3.33</td>
      </tr>
      <tr>
        <th>MasinaTip</th>
        <td>&nbsp;</td>
        <th>FEP</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Buc/mc</th>
        <td>33000</td>
        <th>PFA</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Nr Matrita</th>
        <td>&nbsp;</td>
        <th>E-CTFE</th>
        <td>108.35</td>
        <td>3.28</td>
      </tr>
      <tr>
        <th>Nr cuiburi/matrita</th>
        <td>6</td>
        <th>E-TFE</th>
        <td>121</td>
        <td>3.67</td>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
        <th>NDPE</th>
        <td>60.5</td>
        <td>1.83</td>
      </tr>
    </table>
  </div>
  <div class="table-responsive rounded">
    <table class="table table-hover table-bordered table-light">
      <tr>
        <th>CodProdus</th>
        <td colspan="4">76618536015</td>
      </tr>
      <tr>
        <th>Produs</th>
        <th>Ralu Flow #2</th>
        <th>&nbsp;</th>
        <th>Kg/mc</th>
        <th>g/buc</th>
      </tr>
      <tr>
        <th>Material</th>
        <td>PP</td>
        <th>PP</th>
        <td>&nbsp;</td>
        <td>1.67</td>
      </tr>
      <tr>
        <th>Greutate  Kg/mc</th>
        <td>55</td>
        <th>PP GF</th>
        <td>66</td>
        <td>2.00</td>
      </tr>
      <tr>
        <th>Productie 24h</th>
        <td>1.2</td>
        <th>PES</th>
        <td>101.75</td>
        <td>3.08</td>
      </tr>
      <tr>
        <th>Greutate /buc</th>
        <td>1.67</td>
        <th>PPS</th>
        <td>99</td>
        <td>3.00</td>
      </tr>
      <tr>
        <th>TimpInjectie [sec]</th>
        <td>1.92</td>
        <th>PVDF</th>
        <td>110</td>
        <td>3.33</td>
      </tr>
      <tr>
        <th>MasinaTip</th>
        <td>&nbsp;</td>
        <th>FEP</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Buc/mc</th>
        <td>33000</td>
        <th>PFA</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Nr Matrita</th>
        <td>&nbsp;</td>
        <th>E-CTFE</th>
        <td>108.35</td>
        <td>3.28</td>
      </tr>
      <tr>
        <th>Nr cuiburi/matrita</th>
        <td>6</td>
        <th>E-TFE</th>
        <td>121</td>
        <td>3.67</td>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
        <th>NDPE</th>
        <td>60.5</td>
        <td>1.83</td>
      </tr>
    </table>
  </div>
  <div class="table-responsive rounded">
    <table class="table table-hover table-bordered table-secondary">
      <tr>
        <th>CodProdus</th>
        <td colspan="4">76618536015</td>
      </tr>
      <tr>
        <th>Produs</th>
        <th>Ralu Flow #2</th>
        <th>&nbsp;</th>
        <th>Kg/mc</th>
        <th>g/buc</th>
      </tr>
      <tr>
        <th>Material</th>
        <td>PP</td>
        <th>PP</th>
        <td>&nbsp;</td>
        <td>1.67</td>
      </tr>
      <tr>
        <th>Greutate  Kg/mc</th>
        <td>55</td>
        <th>PP GF</th>
        <td>66</td>
        <td>2.00</td>
      </tr>
      <tr>
        <th>Productie 24h</th>
        <td>1.2</td>
        <th>PES</th>
        <td>101.75</td>
        <td>3.08</td>
      </tr>
      <tr>
        <th>Greutate /buc</th>
        <td>1.67</td>
        <th>PPS</th>
        <td>99</td>
        <td>3.00</td>
      </tr>
      <tr>
        <th>TimpInjectie [sec]</th>
        <td>1.92</td>
        <th>PVDF</th>
        <td>110</td>
        <td>3.33</td>
      </tr>
      <tr>
        <th>MasinaTip</th>
        <td>&nbsp;</td>
        <th>FEP</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Buc/mc</th>
        <td>33000</td>
        <th>PFA</th>
        <td>132</td>
        <td>4.00</td>
      </tr>
      <tr>
        <th>Nr Matrita</th>
        <td>&nbsp;</td>
        <th>E-CTFE</th>
        <td>108.35</td>
        <td>3.28</td>
      </tr>
      <tr>
        <th>Nr cuiburi/matrita</th>
        <td>6</td>
        <th>E-TFE</th>
        <td>121</td>
        <td>3.67</td>
      </tr>
      <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
        <th>NDPE</th>
        <td>60.5</td>
        <td>1.83</td>
      </tr>
    </table>
  </div>
</div>