<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2">
      <div class="card bg-dark">
        <div class="card-body">
           <form method="get">
            <h6 class="text-white">Filtreaza dupa</h6>
            <div class="form-group">
              <input type="text" class="form-control" id="denumire_reper" name="denumire_reper" placeholder="Produs">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="cod_reper" name="cod_reper" placeholder="Cod produs">
            </div>
            <div class="form-group">
              <label for="material" class="text-white">Material:</label>
              <select class="form-control" id="material" name="material" multiple>
			  <?php foreach ($this->materials as $key => $material):?>
				<option value="<?= $material['id']?>"><?= $material['name']?></option>
				<?php endforeach?>
              </select>
            </div>
            <div class="form-group">
              <label for="orderby" class="text-white">Ordoneaza dupa</label>
              <select class="form-control" id="orderby" name="orderby">
                <option>Greutate Kg/mc</option>
                <option>Productie 24h</option>
                <option>Greutate /buc</option>
                <option>TimpInjectie</option>
              </select>
            </div>
            <div class="form-group">
              <select class="form-control" id="sort" name="sort">
                <option>Ascendent</option>
                <option>Descendent</option>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Filtraza</button>
          </form> 
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="table-responsive rounded">
        <table class="table table-hover table-bordered table-light">
          <thead class="thead-light">
            <tr>
              <th>Produs</th>
              <th colspan="4">Ralu Flow #2</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Cod produs</td>
              <td>76618536015</td>
              <td>&nbsp;</td>
              <td>Kg/mc</td>
              <td>g/buc</td>
            </tr>
            <tr>
              <td>Material</td>
              <td>PP</td>
              <td>PP</td>
              <td>&nbsp;</td>
              <td>1.67</td>
            </tr>
            <tr>
              <td>Greutate  Kg/mc</td>
              <td>55</td>
              <td>PP GF</td>
              <td>66</td>
              <td>2.00</td>
            </tr>
            <tr>
              <td>Productie 24h</td>
              <td>1.2</td>
              <td>PES</td>
              <td>101.75</td>
              <td>3.08</td>
            </tr>
            <tr>
              <td>Greutate /buc</td>
              <td>1.67</td>
              <td>PPS</td>
              <td>99</td>
              <td>3.00</td>
            </tr>
            <tr>
              <td>TimpInjectie [sec]</td>
              <td>1.92</td>
              <td>PVDF</td>
              <td>110</td>
              <td>3.33</td>
            </tr>
            <tr>
              <td>MasinaTip</td>
              <td>&nbsp;</td>
              <td>FEP</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Buc/mc</td>
              <td>33000</td>
              <td>PFA</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Nr Matrita</td>
              <td>&nbsp;</td>
              <td>E-CTFE</td>
              <td>108.35</td>
              <td>3.28</td>
            </tr>
            <tr>
              <td>Nr cuiburi/matrita</td>
              <td>6</td>
              <td>E-TFE</td>
              <td>121</td>
              <td>3.67</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>NDPE</td>
              <td>60.5</td>
              <td>1.83</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-responsive rounded">
        <table class="table table-hover table-bordered table-light">
          <thead class="thead-light">
            <tr>
              <th>Produs</th>
              <th colspan="4">Ralu Flow #2</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Cod produs</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>Kg/mc</td>
              <td>g/buc</td>
            </tr>
            <tr>
              <td>Material</td>
              <td>PP</td>
              <td>PP</td>
              <td>&nbsp;</td>
              <td>1.67</td>
            </tr>
            <tr>
              <td>Greutate  Kg/mc</td>
              <td>55</td>
              <td>PP GF</td>
              <td>66</td>
              <td>2.00</td>
            </tr>
            <tr>
              <td>Productie 24h</td>
              <td>1.2</td>
              <td>PES</td>
              <td>101.75</td>
              <td>3.08</td>
            </tr>
            <tr>
              <td>Greutate /buc</td>
              <td>1.67</td>
              <td>PPS</td>
              <td>99</td>
              <td>3.00</td>
            </tr>
            <tr>
              <td>TimpInjectie [sec]</td>
              <td>1.92</td>
              <td>PVDF</td>
              <td>110</td>
              <td>3.33</td>
            </tr>
            <tr>
              <td>MasinaTip</td>
              <td>&nbsp;</td>
              <td>FEP</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Buc/mc</td>
              <td>33000</td>
              <td>PFA</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Nr Matrita</td>
              <td>&nbsp;</td>
              <td>E-CTFE</td>
              <td>108.35</td>
              <td>3.28</td>
            </tr>
            <tr>
              <td>Nr cuiburi/matrita</td>
              <td>6</td>
              <td>E-TFE</td>
              <td>121</td>
              <td>3.67</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>NDPE</td>
              <td>60.5</td>
              <td>1.83</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-responsive rounded">
        <table class="table table-hover table-bordered table-light">
          <thead class="thead-light">
            <tr>
              <th>Produs</th>
              <th colspan="4">Ralu Flow #2</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Produs</td>
              <td>Ralu Flow #2</td>
              <td>&nbsp;</td>
              <td>Kg/mc</td>
              <td>g/buc</td>
            </tr>
            <tr>
              <td>Material</td>
              <td>PP</td>
              <td>PP</td>
              <td>&nbsp;</td>
              <td>1.67</td>
            </tr>
            <tr>
              <td>Greutate  Kg/mc</td>
              <td>55</td>
              <td>PP GF</td>
              <td>66</td>
              <td>2.00</td>
            </tr>
            <tr>
              <td>Productie 24h</td>
              <td>1.2</td>
              <td>PES</td>
              <td>101.75</td>
              <td>3.08</td>
            </tr>
            <tr>
              <td>Greutate /buc</td>
              <td>1.67</td>
              <td>PPS</td>
              <td>99</td>
              <td>3.00</td>
            </tr>
            <tr>
              <td>TimpInjectie [sec]</td>
              <td>1.92</td>
              <td>PVDF</td>
              <td>110</td>
              <td>3.33</td>
            </tr>
            <tr>
              <td>MasinaTip</td>
              <td>&nbsp;</td>
              <td>FEP</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Buc/mc</td>
              <td>33000</td>
              <td>PFA</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Nr Matrita</td>
              <td>&nbsp;</td>
              <td>E-CTFE</td>
              <td>108.35</td>
              <td>3.28</td>
            </tr>
            <tr>
              <td>Nr cuiburi/matrita</td>
              <td>6</td>
              <td>E-TFE</td>
              <td>121</td>
              <td>3.67</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>NDPE</td>
              <td>60.5</td>
              <td>1.83</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-responsive rounded">
        <table class="table table-hover table-bordered table-light">
          <thead class="thead-light">
            <tr>
              <th>Produs</th>
              <th colspan="4">Ralu Flow #2</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Produs</td>
              <td>Ralu Flow #2</td>
              <td>&nbsp;</td>
              <td>Kg/mc</td>
              <td>g/buc</td>
            </tr>
            <tr>
              <td>Material</td>
              <td>PP</td>
              <td>PP</td>
              <td>&nbsp;</td>
              <td>1.67</td>
            </tr>
            <tr>
              <td>Greutate  Kg/mc</td>
              <td>55</td>
              <td>PP GF</td>
              <td>66</td>
              <td>2.00</td>
            </tr>
            <tr>
              <td>Productie 24h</td>
              <td>1.2</td>
              <td>PES</td>
              <td>101.75</td>
              <td>3.08</td>
            </tr>
            <tr>
              <td>Greutate /buc</td>
              <td>1.67</td>
              <td>PPS</td>
              <td>99</td>
              <td>3.00</td>
            </tr>
            <tr>
              <td>TimpInjectie [sec]</td>
              <td>1.92</td>
              <td>PVDF</td>
              <td>110</td>
              <td>3.33</td>
            </tr>
            <tr>
              <td>MasinaTip</td>
              <td>&nbsp;</td>
              <td>FEP</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Buc/mc</td>
              <td>33000</td>
              <td>PFA</td>
              <td>132</td>
              <td>4.00</td>
            </tr>
            <tr>
              <td>Nr Matrita</td>
              <td>&nbsp;</td>
              <td>E-CTFE</td>
              <td>108.35</td>
              <td>3.28</td>
            </tr>
            <tr>
              <td>Nr cuiburi/matrita</td>
              <td>6</td>
              <td>E-TFE</td>
              <td>121</td>
              <td>3.67</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>NDPE</td>
              <td>60.5</td>
              <td>1.83</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-lg-2">&nbsp;</div>
  </div>
</div>