<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2">
      <!-- Filtre -->
      <div class="card bg-dark">
        <div class="card-body">
           <form method="get">
            <h6 class="text-white">Filtreaza dupa</h6>
            <div class="form-group">
              <input type="text" class="form-control" id="denumire_reper" name="denumire_reper" placeholder="Produs">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" id="cod_reper" name="cod_reper" placeholder="Cod produs">
            </div>
            <div class="form-group">
              <label for="material" class="text-white">Material:</label>
              <select class="form-control" id="material" name="material" multiple>
        			  <?php foreach ($this->materials as $key => $material):?>
        				<option value="<?= $material['id']?>"><?= $material['name']?></option>
        				<?php endforeach?>
              </select>
            </div>
            <div class="form-group">
              <label for="orderby" class="text-white">Ordoneaza dupa</label>
              <select class="form-control" id="orderby" name="orderby">
                <option>Greutate Kg/mc</option>
                <option>Productie 24h</option>
                <option>Greutate /buc</option>
                <option>TimpInjectie</option>
              </select>
            </div>
            <div class="form-group">
              <select class="form-control" id="sort" name="sort">
                <option>Ascendent</option>
                <option>Descendent</option>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Filtraza</button>
          </form> 
        </div>
      </div>
      <!-- EOF Filtre -->
    </div>
    <div class="col-lg-8">
      <!-- Produse -->
      <?php foreach ($this->molds as $mold):?>
      <div class="table-responsive rounded">
        <table class="table table-hover table-bordered table-light">
          <thead class="thead-light">
            <tr>
              <th>Produs</th>
              <th colspan="4"><a href="<?= BASE_PATH?>/edit-mold/<?= $mold['id']?>"><?= $mold['denumire_reper']?></a></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Cod produs</td>
              <td><?= $mold['cod_reper']?></td>
              <td>&nbsp;</td>
              <td>Kg/mc</td>
              <td>g/buc</td>
            </tr>
            <tr>
              <td>Material</td>
              <td class="bg-warning">PP</td>
              <td>PP</td>
              <td>&nbsp;</td>
              <td><?= $mold['greutate_fara_cule']?></td>
            </tr>
            <tr>
              <td>Greutate  Kg/mc</td>
              <td class="bg-warning">55</td>
              <td>PP GF</td>
              <td class="bg-warning">66</td>
              <td class="bg-warning">2.00</td>
            </tr>
            <tr>
              <td>Productie 24h</td>
              <td class="bg-warning">1.2</td>
              <td>PES</td>
              <td class="bg-warning">101.75</td>
              <td class="bg-warning">3.08</td>
            </tr>
            <tr>
              <td>Greutate /buc</td>
              <td><?= $mold['greutate_fara_cule']?></td>
              <td>PPS</td>
              <td class="bg-warning">99</td>
              <td class="bg-warning">3.00</td>
            </tr>
            <tr>
              <td>TimpInjectie [sec]</td>
              <td><?= $mold['ciclu_inj']?></td>
              <td>PVDF</td>
              <td class="bg-warning">110</td>
              <td class="bg-warning">3.33</td>
            </tr>
            <tr>
              <td>MasinaTip</td>
              <td class="bg-warning">&nbsp;</td>
              <td>FEP</td>
              <td class="bg-warning">132</td>
              <td class="bg-warning">4.00</td>
            </tr>
            <tr>
              <td>Buc/mc</td>
              <td><?= $mold['cantitate']?></td>
              <td>PFA</td>
              <td class="bg-warning">132</td>
              <td class="bg-warning">4.00</td>
            </tr>
            <tr>
              <td>Nr Matrita</td>
              <td class="bg-warning">&nbsp;</td>
              <td>E-CTFE</td>
              <td class="bg-warning">108.35</td>
              <td class="bg-warning">3.28</td>
            </tr>
            <tr>
              <td>Nr cuiburi/matrita</td>
              <td><?= $mold['nr_cuiburi']?></td>
              <td>E-TFE</td>
              <td class="bg-warning">121</td>
              <td class="bg-warning">3.67</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>NDPE</td>
              <td class="bg-warning">60.5</td>
              <td class="bg-warning">1.83</td>
            </tr>
          </tbody>
        </table>
      </div>
      <?php endforeach?>
      <!-- EOF Produse -->
    </div>
    <div class="col-lg-2">&nbsp;</div>
  </div>
</div>