<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/styles.css">

  <title>Matrite</title>
</head>
<body>

  <section role="main">
    <?= $this->yieldView(); ?>
  </section>

  <script src="vendor/components/jquery/jquery.min.js"></script>
  <script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>