<!doctype html>
<html lang="ro">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="<?= BASE_PATH?>/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="<?= BASE_PATH?>/css/styles.css">

  <title>Matrite</title>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Inapoi sus</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="<?= BASE_PATH?>/index">Lista</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= BASE_PATH?>/add-mold">Adauga matrita</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= BASE_PATH?>/materials">Materiale</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= BASE_PATH?>/users">Utilizatori</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0" method="post" action="<?= BASE_PATH?>/logout">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
      </form>
    </div>
  </nav>

  <section role="main">
    <?= $this->yieldView(); ?>
  </section>

  <script src="<?= BASE_PATH?>/vendor/components/jquery/jquery.min.js"></script>
  <script src="<?= BASE_PATH?>/vendor/twbs/bootstrap/assets/js/vendor/popper.min.js"></script>
  <script src="<?= BASE_PATH?>/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>