<div class="container">

  <form class="form-addmold" method="post">
    <h2 class="form-addmold-heading">Date matrita</h2>

    <table class="table table-bordered">
	    <tbody>
	      <tr>
	        <td>Denumier reper:</td>
	        <td><b>Pall ring 15</b></td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Cod reper:</td>
	        <td>&nbsp;</td>
	        <td>Cantitate:</td>
	        <td>242000 buc/mc</td>
	      </tr>
	      <tr>
	        <td>Cod matrita:</td>
	        <td>&nbsp;</td>
	        <td>Ciclu inj PP:</td>
	        <td>9 sec</td>
	      </tr>
	      <tr>
	        <td>Nr. de cuiburi:</td>
	        <td>8</td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Greutate culee[g]:</td>
	        <td>-</td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Greutate reper fara culee[g]:</td>
	        <td>0.46</td>
	        <td>Dim. matrita [h x l x L]:</td>
	        <td>&nbsp;</td>
	      </tr>
	      <tr>
	        <td>Dimensiuni reper [mm x mm]:</td>
	        <td>15x15</td>
	        <td colspan="2">350x160</td>
	      </tr>
	      <tr>
	        <td>Numar rezistente</td>
	        <td>10</td>
	        <td colspan="2">350x160</td>
	      </tr>
	      <tr>
	        <td>Diametru inel de centrare:</td>
	        <td>110</td>
	        <td colspan="2">&nbsp;</td>
	      </tr>
	    </tbody>
	  </table>

	  <table class="table table-bordered">
	    <tbody>
	      <tr>
	        <td><b>Pregatire matrita:</b>
	        	<div class="radio">
				  <label><input type="radio" name="optradio">ungere coloane</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">modif. poanson data</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">modif. poanson material</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">verificat duza calda</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">verificat functionare bacuri</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">verificat pozitie bacuri</label>
				</div>
	        </td>
	        <td>&nbsp;</td>
	      </tr>
	      <tr>
	        <td><b>Demontare matrita de pe masina:</b>
	        	<div class="radio">
				  <label><input type="radio" name="optradio">Verificat ultima injectie</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">verificat pozitie bacuri</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">suflat aer comprimat</label>
				</div>
				<div class="radio">
				  <label><input type="radio" name="optradio">conservat matrit</label>
				</div>
				</div>
	        </td>
	        <td><b><u>Observatii</u></b></td>
	      </tr>
      	</tbody>
	  </table>

	  <table class="table table-bordered">
	    <tbody>
	      <tr>
	      	<td rowspan="2">Rezistente</td>
	      	<td rowspan="2">Cuiburi</td>
	      	<td colspan="2" rowspan="2">Legaturi rezistente</td>
	      	<td colspan="2">legaturi sonde</td>
	      	<td rowspan="2">&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>+</td>
      	  	<td>-</td>
      	  </tr>
      	  <tr>
      	  	<td>1</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>2</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>3</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>4</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>5</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>6</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>7</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>8</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>9</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	  <tr>
      	  	<td>10</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  	<td>&nbsp;</td>
      	  </tr>
      	</tbody>
	  </table>
	  
	  <table class="table table-bordered">
	    <tbody>
	      <tr>
			<td>1 Rezistente cuib</td>
			<td>4x80 TC</td>
			<td>8 buc</td>
  	  	  </tr>
  	  	  <tr>
			<td>2 Rezistenta centrala</td>
			<td>6,5x80 TC 1 buc</td>
			<td>1 buc</td>
  	  	  </tr>
  	  	  <tr>
			<td>3 rezistenta bloc</td>
			<td>9,5x298 TC 1 buc</td>
			<td>1 buc</td>
  	  	  </tr>
      	</tbody>
	  </table>
	  <p>inel O 6x2</p>
  </form>

</div>
