<div class="container h-200 jumbotron">
  <?php $this->partial('views/alert.phtml')?>
  <div class="row h-200 justify-content-center align-items-center">
  	<div class="col-lg-5">
	  <form method="post">
	    <h2>Va rugam sa va logati</h2>
	    <div class="form-group">
		    <label for="inputEmail" class="sr-only">Email</label>
		    <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email" required autofocus>
		</div>
		<div class="form-group">
		    <label for="inputPassword" class="sr-only">Parola</label>
		    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Parola" required>
		</div>
	    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
	  </form>
	</div>
  </div>
</div>