  <div class="table-responsive container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Email</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->users as $key => $user):?>
        <tr>
          <td><?= ($key + 1)?></td>
          <td><?= $user['email']?></td>
          <td><a href="#">Edit</a></td>
        </tr>
        <?php endforeach?>
      </tbody>
    </table>
  </div>